/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { ExampleOwner, ExampleOwnerInterface } from "../ExampleOwner";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnerSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "changeOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546201000033810262010000600160b01b0319909216919091178083556040519190046001600160a01b031691907f342827c97908e5e2f71151c08502a66d44b6f758e3ac2f1de95f02eb95f0a735908290a36101a7806100766000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063893d20e81461003b578063a6f9dae114610069575b600080fd5b6000546201000090046001600160a01b03166040516001600160a01b03909116815260200160405180910390f35b61007c610077366004610141565b61007e565b005b6000546201000090046001600160a01b031633146100d85760405162461bcd60e51b815260206004820152601360248201527221b0b63632b91034b9903737ba1037bbb732b960691b604482015260640160405180910390fd5b600080546040516001600160a01b03808516936201000090930416917f342827c97908e5e2f71151c08502a66d44b6f758e3ac2f1de95f02eb95f0a73591a3600080546001600160a01b03909216620100000262010000600160b01b0319909216919091179055565b60006020828403121561015357600080fd5b81356001600160a01b038116811461016a57600080fd5b939250505056fea26469706673582212206501ba03af195111e5a71222a5077a47dae577b357696d0fb6fcdfc6e846289a64736f6c634300080d0033";

type ExampleOwnerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExampleOwnerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExampleOwner__factory extends ContractFactory {
  constructor(...args: ExampleOwnerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "ExampleOwner";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ExampleOwner> {
    return super.deploy(overrides || {}) as Promise<ExampleOwner>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ExampleOwner {
    return super.attach(address) as ExampleOwner;
  }
  connect(signer: Signer): ExampleOwner__factory {
    return super.connect(signer) as ExampleOwner__factory;
  }
  static readonly contractName: "ExampleOwner";
  public readonly contractName: "ExampleOwner";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExampleOwnerInterface {
    return new utils.Interface(_abi) as ExampleOwnerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExampleOwner {
    return new Contract(address, _abi, signerOrProvider) as ExampleOwner;
  }
}
