/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ContractDeployer } from "./ContractDeployer";
export type { ContractRegistry } from "./ContractRegistry";
export type { ExampleBallot } from "./ExampleBallot";
export type { ExampleOwner } from "./ExampleOwner";
export type { ExampleOwnerV2 } from "./ExampleOwnerV2";
export type { ExampleStorage } from "./ExampleStorage";
export type { UpgradeableDeployer } from "./UpgradeableDeployer";
